FROM node:16-alpine

WORKDIR /app
COPY ./ /app

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

RUN npm install
RUN npm rebuild node-sass

CMD [ "npm", "start" ]