FROM node:16-alpine

WORKDIR /app
COPY ./ /app

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

RUN npm install -g node-sass@6.0.1
RUN npm install
CMD [ "npm", "start" ]