FROM node:16-alpine

RUN apk add --no-cache curl zsh git emacs vim;

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

# root only for dev
USER root

# zsh only for dev
ARG OH_MY_ZSH_THEME=cloud
RUN set -eux; \
		sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"; \
		sed -i "s/\(^ZSH_THEME=\).*/\1$OH_MY_ZSH_THEME/" ~/.zshrc;

WORKDIR /app
COPY frontend /app

RUN npm install
RUN npm rebuild node-sass

CMD	["npm", "start"]
