export interface GameInterface {
  ballX: number,
  ballY: number,
  p1Y: number,
  p2Y: number,
  paddleHeight: number,
  p1Name: string,
  p2Name: string,
  viewerNames: string[],
  p1score: number,
  p2score: number,
  winner: number,
  paddleOffcet: number,
  ballRadius: number,
  paddleThickness: number,
}
